name: Debug Gradlew

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Where am I
        run: |
          pwd
          ls -la

      - name: List all gradlew
        run: |
          find . -name "gradlew*"

      - name: Try chmod
        run: chmod +x gradlew